name: Smarthome
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2
  flutter_reactive_ble: ^5.0.2
  flutter_blue_plus: ^1.35.5
  uuid: ^4.0.0
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "Anhnen.jpg"

flutter:
  uses-material-design: true
  assets:
    - Anhnen.jpg
